services:
  # DB 서버 이미지
  mysql:
    image: mysql:8.0
    container_name: test-mysql
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_ROOT_PASSWORD: tagtag1010
      TZ: Asia/Seoul
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -p$$MYSQL_ROOT_PASSWORD --silent" ]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

  # 내 서버 이미지
  target:
    build: .
    image: user-target:latest
    container_name: user-target
    ports:
      - "8085:8085"
    volumes:
      - logs:/app/logs  # 해당 경로에 로그를 작성
    environment:
      TZ: Asia/Seoul
      # 중요: JDBC URL의 host는 localhost가 아니라 서비스명 mysql
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/test_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: tagtag1010
    restart: unless-stopped

  # 포워더 이미지
  forwarder:
    image: ${FORWARDER_IMAGE}
    container_name: mcp-forwarder
    depends_on: [target]
    volumes:
      - logs:/logs:ro  # 로그 파일을 읽음
    environment:
      MCP_LOG_INGEST_URL: "${MCP_DOMAIN}/api/servers/${SERVER_NAME}/ingest/logs"
      MCP_METRIC_INGEST_URL: "${MCP_DOMAIN}/api/servers/${SERVER_NAME}/ingest/metrics"
      MCP_HEALTH_INGEST_URL: "${MCP_DOMAIN}/api/servers/${SERVER_NAME}/ingest/health"
      HEALTH_URL: "http://target:9090/actuator/health"  # 헬스 체크 대상 URL
      MCP_TOKEN: "${INGEST_TOKEN}"
      DISCORD_WEBHOOK_URL: "${DISCORD_WEBHOOK_URL}"
      LOG_PATH: "/logs/application.log"
      # target:9090 을 통해 내 서버의 9090 포트를 이용해 actuator 정보를 가져옴. 외부에는 노출 X(보안에 최적)
      ACTUATOR_URL: "http://target:9090/actuator/metrics"
    restart: unless-stopped


volumes:
  logs:
  mysql-data:
